// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoggerUIClient is the client API for LoggerUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggerUIClient interface {
	// ListEngineSpecs returns a list of Logging Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LoggerUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type loggerUIClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerUIClient(cc grpc.ClientConnInterface) LoggerUIClient {
	return &loggerUIClient{cc}
}

func (c *loggerUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LoggerUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggerUI_ServiceDesc.Streams[0], "/v1.LoggerUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &loggerUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggerUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type loggerUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *loggerUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggerUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.LoggerUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerUIServer is the server API for LoggerUI service.
// All implementations must embed UnimplementedLoggerUIServer
// for forward compatibility
type LoggerUIServer interface {
	// ListEngineSpecs returns a list of Logging Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, LoggerUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedLoggerUIServer()
}

// UnimplementedLoggerUIServer must be embedded to have forward compatible implementations.
type UnimplementedLoggerUIServer struct {
}

func (UnimplementedLoggerUIServer) ListEngineSpecs(*ListEngineSpecsRequest, LoggerUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedLoggerUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedLoggerUIServer) mustEmbedUnimplementedLoggerUIServer() {}

// UnsafeLoggerUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggerUIServer will
// result in compilation errors.
type UnsafeLoggerUIServer interface {
	mustEmbedUnimplementedLoggerUIServer()
}

func RegisterLoggerUIServer(s grpc.ServiceRegistrar, srv LoggerUIServer) {
	s.RegisterService(&LoggerUI_ServiceDesc, srv)
}

func _LoggerUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggerUIServer).ListEngineSpecs(m, &loggerUIListEngineSpecsServer{stream})
}

type LoggerUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type loggerUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *loggerUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggerUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LoggerUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoggerUI_ServiceDesc is the grpc.ServiceDesc for LoggerUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggerUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LoggerUI",
	HandlerType: (*LoggerUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _LoggerUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _LoggerUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logger-ui.proto",
}
